/*#include <wasi/api.h>

#define EPERM              __WASI_ERRNO_PERM
#define ENOENT             __WASI_ERRNO_NOENT
#define ESRCH              __WASI_ERRNO_SRCH
#define EINTR              __WASI_ERRNO_INTR
#define EIO                __WASI_ERRNO_IO
#define ENXIO              __WASI_ERRNO_NXIO
#define E2BIG              __WASI_ERRNO_2BIG
#define ENOEXEC            __WASI_ERRNO_NOEXEC
#define EBADF              __WASI_ERRNO_BADF
#define ECHILD             __WASI_ERRNO_CHILD
#define EAGAIN             __WASI_ERRNO_AGAIN
#define ENOMEM             __WASI_ERRNO_NOMEM
#define EACCES             __WASI_ERRNO_ACCES
#define EFAULT             __WASI_ERRNO_FAULT
#define EBUSY              __WASI_ERRNO_BUSY
#define EEXIST             __WASI_ERRNO_EXIST
#define EXDEV              __WASI_ERRNO_XDEV
#define ENODEV             __WASI_ERRNO_NODEV
#define ENOTDIR            __WASI_ERRNO_NOTDIR
#define EISDIR             __WASI_ERRNO_ISDIR
#define EINVAL             __WASI_ERRNO_INVAL
#define ENFILE             __WASI_ERRNO_NFILE
#define EMFILE             __WASI_ERRNO_MFILE
#define ENOTTY             __WASI_ERRNO_NOTTY
#define ETXTBSY            __WASI_ERRNO_TXTBSY
#define EFBIG              __WASI_ERRNO_FBIG
#define ENOSPC             __WASI_ERRNO_NOSPC
#define ESPIPE             __WASI_ERRNO_SPIPE
#define EROFS              __WASI_ERRNO_ROFS
#define EMLINK             __WASI_ERRNO_MLINK
#define EPIPE              __WASI_ERRNO_PIPE
#define EDOM               __WASI_ERRNO_DOM
#define ERANGE             __WASI_ERRNO_RANGE
#define EDEADLK            __WASI_ERRNO_DEADLK
#define ENAMETOOLONG       __WASI_ERRNO_NAMETOOLONG
#define ENOLCK             __WASI_ERRNO_NOLCK
#define ENOSYS             __WASI_ERRNO_NOSYS
#define ENOTEMPTY          __WASI_ERRNO_NOTEMPTY
#define ELOOP              __WASI_ERRNO_LOOP
#define ENOMSG             __WASI_ERRNO_NOMSG
#define EIDRM              __WASI_ERRNO_IDRM
#define ENOLINK            __WASI_ERRNO_NOLINK
#define EPROTO             __WASI_ERRNO_PROTO
#define EMULTIHOP          __WASI_ERRNO_MULTIHOP
#define EBADMSG            __WASI_ERRNO_BADMSG
#define EOVERFLOW          __WASI_ERRNO_OVERFLOW
#define EILSEQ             __WASI_ERRNO_ILSEQ
#define ENOTSOCK           __WASI_ERRNO_NOTSOCK
#define EDESTADDRREQ       __WASI_ERRNO_DESTADDRREQ
#define EMSGSIZE           __WASI_ERRNO_MSGSIZE
#define EPROTOTYPE         __WASI_ERRNO_PROTOTYPE
#define ENOPROTOOPT        __WASI_ERRNO_NOPROTOOPT
#define EPROTONOSUPPORT    __WASI_ERRNO_PROTONOSUPPORT
#define EAFNOSUPPORT       __WASI_ERRNO_AFNOSUPPORT
#define EADDRINUSE         __WASI_ERRNO_ADDRINUSE
#define EADDRNOTAVAIL      __WASI_ERRNO_ADDRNOTAVAIL
#define ENETDOWN           __WASI_ERRNO_NETDOWN
#define ENETUNREACH        __WASI_ERRNO_NETUNREACH
#define ENETRESET          __WASI_ERRNO_NETRESET
#define ECONNABORTED       __WASI_ERRNO_CONNABORTED
#define ECONNRESET         __WASI_ERRNO_CONNRESET
#define ENOBUFS            __WASI_ERRNO_NOBUFS
#define EISCONN            __WASI_ERRNO_ISCONN
#define ENOTCONN           __WASI_ERRNO_NOTCONN
#define ETIMEDOUT          __WASI_ERRNO_TIMEDOUT
#define ECONNREFUSED       __WASI_ERRNO_CONNREFUSED
#define EHOSTUNREACH       __WASI_ERRNO_HOSTUNREACH
#define EALREADY           __WASI_ERRNO_ALREADY
#define EINPROGRESS        __WASI_ERRNO_INPROGRESS
#define ESTALE             __WASI_ERRNO_STALE
#define EDQUOT             __WASI_ERRNO_DQUOT
#define ECANCELED          __WASI_ERRNO_CANCELED
#define EOWNERDEAD         __WASI_ERRNO_OWNERDEAD
#define ENOTRECOVERABLE    __WASI_ERRNO_NOTRECOVERABLE



// Codes without a wasi equivalent, make sure they start
// above the wasi ones, which are dense [1,76].
// Also try to fit the codes in a single byte signed wasm SLEB.

#define ENOSTR          100
#define EBFONT          101
#define EBADSLT         102
#define EBADRQC         103
#define ENOANO          104
#define ENOTBLK         105
#define ECHRNG          106
#define EL3HLT          107
#define EL3RST          108
#define ELNRNG          109
#define EUNATCH         110
#define ENOCSI          111
#define EL2HLT          112
#define EBADE           113
#define EBADR           114
#define EXFULL          115
#define ENODATA         116
#define ETIME           117
#define ENOSR           118
#define ENONET          119
#define ENOPKG          120
#define EREMOTE         121
#define EADV            122
#define ESRMNT          123
#define ECOMM           124
#define EDOTDOT         125
#define ENOTUNIQ        126
#define EBADFD          127
#define EREMCHG         128
#define ELIBACC         129
#define ELIBBAD         130
#define ELIBSCN         131
#define ELIBMAX         132
#define ELIBEXEC        133
#define ERESTART        134
#define ESTRPIPE        135
#define EUSERS          136
#define ESOCKTNOSUPPORT 137
#define EOPNOTSUPP      138
#define EPFNOSUPPORT    139
#define ESHUTDOWN       140
#define ETOOMANYREFS    141
#define EHOSTDOWN       142
#define EUCLEAN         143
#define ENOTNAM         144
#define ENAVAIL         145
#define EISNAM          146
#define EREMOTEIO       147
#define ENOMEDIUM       148
#define EMEDIUMTYPE     149
#define ENOKEY          150
#define EKEYEXPIRED     151
#define EKEYREVOKED     152
#define EKEYREJECTED    153
#define ERFKILL         154
#define EHWPOISON       155
#define EL2NSYNC        156

// codes which musl defines as aliases

#define EWOULDBLOCK     EAGAIN
#define EDEADLOCK       EDEADLK
#define ENOTSUP         EOPNOTSUPP*/

/* Modified by Benoit Baudaux 13/06/2023 */

#define EPERM            1
#define ENOENT           2
#define ESRCH            3
#define EINTR            4
#define EIO              5
#define ENXIO            6
#define E2BIG            7
#define ENOEXEC          8
#define EBADF            9
#define ECHILD          10
#define EAGAIN          11
#define ENOMEM          12
#define EACCES          13
#define EFAULT          14
#define ENOTBLK         15
#define EBUSY           16
#define EEXIST          17
#define EXDEV           18
#define ENODEV          19
#define ENOTDIR         20
#define EISDIR          21
#define EINVAL          22
#define ENFILE          23
#define EMFILE          24
#define ENOTTY          25
#define ETXTBSY         26
#define EFBIG           27
#define ENOSPC          28
#define ESPIPE          29
#define EROFS           30
#define EMLINK          31
#define EPIPE           32
#define EDOM            33
#define ERANGE          34
#define EDEADLK         35
#define ENAMETOOLONG    36
#define ENOLCK          37
#define ENOSYS          38
#define ENOTEMPTY       39
#define ELOOP           40
#define EWOULDBLOCK     EAGAIN
#define ENOMSG          42
#define EIDRM           43
#define ECHRNG          44
#define EL2NSYNC        45
#define EL3HLT          46
#define EL3RST          47
#define ELNRNG          48
#define EUNATCH         49
#define ENOCSI          50
#define EL2HLT          51
#define EBADE           52
#define EBADR           53
#define EXFULL          54
#define ENOANO          55
#define EBADRQC         56
#define EBADSLT         57
#define EDEADLOCK       EDEADLK
#define EBFONT          59
#define ENOSTR          60
#define ENODATA         61
#define ETIME           62
#define ENOSR           63
#define ENONET          64
#define ENOPKG          65
#define EREMOTE         66
#define ENOLINK         67
#define EADV            68
#define ESRMNT          69
#define ECOMM           70
#define EPROTO          71
#define EMULTIHOP       72
#define EDOTDOT         73
#define EBADMSG         74
#define EOVERFLOW       75
#define ENOTUNIQ        76
#define EBADFD          77
#define EREMCHG         78
#define ELIBACC         79
#define ELIBBAD         80
#define ELIBSCN         81
#define ELIBMAX         82
#define ELIBEXEC        83
#define EILSEQ          84
#define ERESTART        85
#define ESTRPIPE        86
#define EUSERS          87
#define ENOTSOCK        88
#define EDESTADDRREQ    89
#define EMSGSIZE        90
#define EPROTOTYPE      91
#define ENOPROTOOPT     92
#define EPROTONOSUPPORT 93
#define ESOCKTNOSUPPORT 94
#define EOPNOTSUPP      95
#define ENOTSUP         EOPNOTSUPP
#define EPFNOSUPPORT    96
#define EAFNOSUPPORT    97
#define EADDRINUSE      98
#define EADDRNOTAVAIL   99
#define ENETDOWN        100
#define ENETUNREACH     101
#define ENETRESET       102
#define ECONNABORTED    103
#define ECONNRESET      104
#define ENOBUFS         105
#define EISCONN         106
#define ENOTCONN        107
#define ESHUTDOWN       108
#define ETOOMANYREFS    109
#define ETIMEDOUT       110
#define ECONNREFUSED    111
#define EHOSTDOWN       112
#define EHOSTUNREACH    113
#define EALREADY        114
#define EINPROGRESS     115
#define ESTALE          116
#define EUCLEAN         117
#define ENOTNAM         118
#define ENAVAIL         119
#define EISNAM          120
#define EREMOTEIO       121
#define EDQUOT          122
#define ENOMEDIUM       123
#define EMEDIUMTYPE     124
#define ECANCELED       125
#define ENOKEY          126
#define EKEYEXPIRED     127
#define EKEYREVOKED     128
#define EKEYREJECTED    129
#define EOWNERDEAD      130
#define ENOTRECOVERABLE 131
#define ERFKILL         132
#define EHWPOISON       133

